name: getx_timer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  advertising_id: ^2.0.0
  audioplayers: ^0.20.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_mobile_ads: ^0.13.4
  sizer: ^2.0.13
  sleek_circular_slider: ^2.0.1
  video_player: ^2.2.0
  wakelock: ^0.5.4

dependency_overrides:
  wakelock: 0.5.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/movie/
    - assets/sounds/
